name: tsgm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - cudatoolkit==10.1
  - pytorch=1.8.1
  - torchaudio==0.8.1
  - torchvision==0.9.1
  - numpy=1.21.6
  - matplotlib=3.3.2
  - imageio=2.21.3
  - imageio-ffmpeg=0.4.7
  - pip=21.3.1
  - pip:
    - absl-py==1.2.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - astor==0.8.1
    - black==21.4b2
    - braceexpand==0.1.7
    - cachetools==5.2.0
    - certifi==2022.9.14
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gast==0.5.3
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.1
    - gym==0.21.0
    - gym-notices==0.0.8
    - h5py==3.7.0
    - hydra-core==1.2.0
    - idna==3.4
    - ifcfg==0.23
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iopath==0.1.9
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lmdb==1.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mock==4.0.3
    - moviepy==2.0.0.dev2
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - oauthlib==3.2.1
    - objectio==0.2.29
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - parmap==1.6.0
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pickle5==0.0.12
    - portalocker==2.5.1
    - proglog==0.1.10
    - promise==2.3
    - protobuf==3.20.2
    - psutil==5.9.2
    - pyasn1==0.5.0rc2
    - pyasn1-modules==0.3.0rc1
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pywavelets==1.3.0
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-fmm==2022.8.15
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - simplejson==3.17.6
    - tabulate==0.8.10
    - termcolor==2.0.1
    - toml==0.10.2
    - typed-ast==1.5.4
    - typer==0.6.1
    - urllib3==1.26.12
    - wandb==0.13.3
    - wheel==0.37.1
    - yacs==0.1.8
    - zipp==3.8.1
prefix: /home/blackfoot/anaconda3/envs/tsgm
