name: tsgm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - numpy=1.21.6
  - matplotlib=3.3.2
  - imageio=2.21.3
  - Pillow=8.3.2
  - pip=22.1.2
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - pandas
prefix: ~/anaconda3/envs/tsgm
