name: tsgm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - attrs=22.1.0=pyh71513ae_1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.9.14=ha878542_0
  - cmake=3.14.0=h52cb24c_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.10.4=h0708190_1
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - imageio=2.21.3=pyhfa7a67d_0
  - imageio-ffmpeg=0.4.7=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.2=py37h7cecad7_1
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - llvmlite=0.36.0=py37h9d7f4d0_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37h4f6019d_1
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numba=0.53.1=py37hb11d6e1_1
  - numpy=1.21.6=py37h976b520_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h7f8727e_0
  - pillow=8.3.2=py37h0f21c89_0
  - pip=22.1.2=py37h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - quaternion=2022.4.1=py37h540881e_0
  - readline=8.1.2=h7f8727e_1
  - rhash=1.4.1=h3c74f83_1
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37hf2a6cf1_0
  - setuptools=63.4.1=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.39.2=h5082296_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py37h540881e_3
  - tqdm=4.64.1=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.4=h9c3ff4c_1001
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.2.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - astor==0.8.1
    - black==21.4b2
    - braceexpand==0.1.7
    - cachetools==5.2.0
    - certifi==2022.9.14
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gast==0.5.3
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.1
    - gym==0.21.0
    - gym-notices==0.0.8
    - h5py==3.7.0
    - hydra-core==1.2.0
    - idna==3.4
    - ifcfg==0.23
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iopath==0.1.9
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lmdb==1.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mock==4.0.3
    - moviepy==2.0.0.dev2
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - oauthlib==3.2.1
    - objectio==0.2.29
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - parmap==1.6.0
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pickle5==0.0.12
    - portalocker==2.5.1
    - proglog==0.1.10
    - promise==2.3
    - protobuf==3.20.2
    - psutil==5.9.2
    - pyasn1==0.5.0rc2
    - pyasn1-modules==0.3.0rc1
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pywavelets==1.3.0
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-fmm==2022.8.15
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - simplejson==3.17.6
    - tabulate==0.8.10
    - tb-nightly==2.11.0a20220914
    - tensorboard==1.13.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.14.0rc0
    - termcolor==2.0.1
    - toml==0.10.2
    - torch==1.8.1+cu101
    - torchaudio==0.8.1
    - torchvision==0.9.1+cu101
    - typed-ast==1.5.4
    - typer==0.6.1
    - urllib3==1.26.12
    - wandb==0.13.3
    - webdataset==0.1.40
    - werkzeug==2.2.2
    - wheel==0.37.1
    - yacs==0.1.8
    - zipp==3.8.1
prefix: /home/blackfoot/anaconda3/envs/tsgm
